### PR TITLE
Updated Linux project files to work with the new project structure.

### PR DESCRIPTION
**Pull request by SpartanJ**
Hi Tom,
i updated the Linux project files to work with the new project structure, removed the old files, and also added the new article ( nº 08 ).

( I know i can merge it, but I will not merge it without your authorization! )

Regards,
Martín

### CODE REVIEW

**Comment by tomdalling** [comment]
Thanks Martín. I appreciate the help!

**Comment by SpartanJ** [comment]
No problem!

I tested a little bit the articles and from 04 to 08 the camera seen to be too near to the object, i can't see almost anything. If i change the initial camera z position and modify the far plane accordingly i can see everything just right. For example, in article 04 i changed the camera z position to 150 and augmented the far plane to be able to see the object ( [broken](http://i.imgur.com/XK9P5jd.png), [fixed](http://i.imgur.com/JO6HnVy.png) ).

**Comment by tomdalling** [comment]
I can't replicate it on OSX in Xcode, but it sounds like a problem with the field of view in the camera. Is GLM_FORCE_RADIANS defined during compilation? It could be a radians/degrees mismatch.

**Comment by SpartanJ** [comment]
Exactly, that was the problem! I pushed the fix. Thanks!

**Comment by tomdalling** [comment]
No problem. Thanks for the help!

**Pull request merged**
